# NOTEBOOK 17 Fancy Indexing
---

You use indexing (e.g. `x[3]`) or slicing (e.g. `x[2:5]`) to select or assign specific elements in e.g. numpy arrays and lists. Here we discuss an alternative method. Instead of a specific index or slice you use a list of indices to select items from an array. This approach is called **fancy indexing**. We will show a few cases where fancy indexing can be used. It is important to mention here that fancy indexing works for numpy arrays only (so not for lists!). Another, but actually quite similar, method to select items from an array is called **masking**. Using a mask you can select items of an array that satisfy a specific condition (e.g. all items larger than zero).

## Fancy Indexing

Let's look at a simple example where we have defined a numpy array containing some outcomes of a throw of a dice:


In [25]:
import random

import numpy as np

throws = np.array([1, 5, 2, 3, 6, 6, 1], dtype=int)
print(throws)

[1 5 2 3 6 6 1]


The array `throws` contains 7 items with integer values between 1 and 6. If you require the items at index 2, 4 and 5 you can use:

In [26]:
indices = [2, 4, 5]

selection = throws[indices]
print(selection)

[2 6 6]


So instead of providing a number as an index or a specific slice, you can provide a list (you can also use a numpy array with integers to specify the indices) of integers between square brackets to select specific items of the array. The output is again an array containing the items at the specified indices.

As with indexing and slicing, you can use fancy indexing to assign values to specific items of an array:

In [27]:
throws[indices] = throws[indices] * -1
# or throws[indices] *= -1 for short
print(throws)

[ 1  5 -2  3 -6 -6  1]


As you can see all items at the indices specified by `indices` are multiplied by -1.

## Masking

Although you learned three different ways to extract items from an array (indexing, slicing and fancy-indexing) there is even another method for this purpose called masking. This method allows to select items in an array based on some criteria. Again we take an example to illustrate how it works. We define an array with marks ranging from 1 to 10:

In [28]:
marks = np.array([7.5, 4.0, 8.0, 5.3, 6.5, 10.0, 3.5, 5.5])

We now want to extract all marks smaller than 6.0. To do this we create a mask which is an array of Booleans specifying for each item if the condition is satisfied `True` or `False`:


In [29]:
mask = marks < 6.0
print(mask)

[False  True False  True False False  True  True]


In the statement `mask = marks < 6.0` Python applies the conditional statement ($< 6.0$) for each item of the array and stores the result `True` or `False` in the array `mask`. Now the Boolean array can be used to extract the data:

In [30]:
onvoldoendes = marks[mask]
print(onvoldoendes)

[4.  5.3 3.5 5.5]


If you use a Boolean array (`mask`) as indices, the result is that all items are retrieved for which the value in the Boolean array is `True`. In this case the 2nd, 4th, 7th and 8th items in `mask` are `True` so the 2nd, 4th, 7th and 8th items in `marks` are retrieved.

You can also apply multiple conditions by using logical operators. Unfortunately python's standard logical operators `and`, `or` and `not` will not work on arrays as they do not perform the operator element-wise (they try to compare the array as a whole and that of course does not make sense). The solution is to use the bitwise operators `&` (logical and), `|` (logical or), `~` (logical not). So if you like to round all marks in the array that have a value larger than 5.0 and smaller than 6.0 to an integer value you can do the following:

In [31]:
marks = np.array([7.5, 4.0, 8.0, 5.3, 6.5, 10.0, 3.5, 5.5])

# create the mask
mask = (marks > 5.0) & (marks < 6)
print(mask)

# round the selected items to integer values
marks[mask] = np.around(marks[mask])

print(marks)

[False False False  True False False False  True]
[ 7.5  4.   8.   5.   6.5 10.   3.5  6. ]


---
**Assignment 1**

In a simulation of $N=100$ bouncing balls we have a numpy array `h` that contains the current heights (above the floor) of all balls. Furthermore we have an array `v` of velocities in which a negative velocity is towards the floor and a positive velocity means the ball is moving in the upward direction. The floor is positioned at a height equal to zero. For convenience we create a current state in the simulation using the random generators:

- Create a numpy array `h` that contains 100 random (uniform) positions between 0 and 1.
- Create a numpy array `v` that contain 100 random (uniform) velocities between between -0.5 and 0.5

In [28]:
# =============== YOUR CODE GOES HERE =================
import numpy as np

h = np.random.uniform(0, 1, 100)
v = np.random.uniform(-0.5,0.5,100)

print(h)
print(v)

[0.38805532 0.84464768 0.75306615 0.4253609  0.74932567 0.17966058
 0.78973313 0.78173085 0.90527069 0.73114864 0.91718697 0.75655068
 0.77668966 0.59539219 0.91009199 0.41990748 0.58265527 0.16316952
 0.69727445 0.95807949 0.80158609 0.00231416 0.23689254 0.85340604
 0.47443767 0.30863259 0.01346463 0.29780038 0.49148361 0.86282663
 0.36493583 0.07789021 0.45232248 0.31622943 0.1025726  0.15509557
 0.03553386 0.56723568 0.75066442 0.36805237 0.32506863 0.02144165
 0.8157987  0.55512502 0.17687611 0.34567029 0.62383599 0.50023641
 0.18587797 0.02855303 0.76388801 0.7411376  0.22613316 0.74254187
 0.10176707 0.9002542  0.79983916 0.92835058 0.3425834  0.7417139
 0.11496404 0.03969322 0.4109745  0.8841312  0.64617565 0.13523553
 0.9725393  0.90890561 0.30468851 0.43865161 0.17651067 0.40383737
 0.4028101  0.61828965 0.37340318 0.79446698 0.3509429  0.93087972
 0.65454465 0.11690154 0.97445219 0.0558858  0.72879644 0.38615875
 0.49934361 0.50360912 0.70546037 0.0429303  0.11828468 0.41873

Some balls will be in contact with the floor (i.e. the height $<$ radius). 
- Create a mask `contact` that is True if the ball is in contact and False otherwise. Take a radius of $r=0.05$.

In [29]:
# =============== YOUR CODE GOES HERE =================
contact = (h < 0.05)
print(contact)

[False False False False False False False False False False False False
 False False False False False False False False False  True False False
 False False  True False False False False False False False False False
  True False False False False  True False False False False False False
 False  True False False False False False False False False False False
 False  True False False False False False False False False False False
 False False False False False False False False False False False False
 False False False  True False False  True False False False False False
 False False False False]


If the ball is in contact and the velocity is negative, obviously the ball bounces, so the velocity should change sign.

- Create a mask `bounce` that is True if the ball is bouncing.
- Use the mask `bounce` to change the array `v` such that balls that are in contact have their velocity changed in sign.

In [36]:
# =============== YOUR CODE GOES HERE =================
bounce = (h < 0.05) & (v < 0)
print(bounce)

v[bounce] = v[bounce]*-1


[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False]
[-0.49489447 -0.21341451  0.06440004 -0.24985007  0.09299196 -0.43192963
  0.33158052 -0.47145446  0.13460879  0.25310288  0.16990324 -0.03370488
 -0.25672496  0.03870675  0.32160865  0.15312903  0.42586467 -0.44755239
  0.12687644  0.26049426  0.26252012  0.05037302  0.06360073 -0.28707536
 -0.2401995  -0.09129501  0.49513038 -0.04048494 -0.19181149  0.22443213
 -0.49752382 -0.17039732 