# NOTEBOOK 20 Nesting
---


Nesting in Python refers to the practice of placing one or more code structures (such as loops, conditional statements, or functions) inside another. It involves the indentation of code blocks to indicate their hierarchical relationship. The most common use of nesting occurs with loops and conditional statements.

## Nested loops

Nested loops involve placing one loop inside another, like this:


In [1]:
# example of nesting for-loops
for i in range(3):
    # inside outer loop
    for j in range(2):
        # inside inner loop
        print(i, j)


0 0
0 1
1 0
1 1
2 0
2 1


Here, the inner loop (with `j`) is nested within the outer loop (with `i`). The indentation levels help signify the scope of each loop.

---
**Assignment 1**

Multiplication Table Generator.

Create a program that takes an integer as input from the user and prints the multiplication table for all numbers upto that number. For example if you use 12 as an input number it should print:

```
    1    2    3    4    5    6    7    8    9   10   11   12
    2    4    6    8   10   12   14   16   18   20   22   24
    3    6    9   12   15   18   21   24   27   30   33   36
    4    8   12   16   20   24   28   32   36   40   44   48
    5   10   15   20   25   30   35   40   45   50   55   60
    6   12   18   24   30   36   42   48   54   60   66   72
    7   14   21   28   35   42   49   56   63   70   77   84
    8   16   24   32   40   48   56   64   72   80   88   96
    9   18   27   36   45   54   63   72   81   90   99  108
   10   20   30   40   50   60   70   80   90  100  110  120
```


In [141]:
# =============== YOUR CODE GOES HERE =================
def table(n):
    for i in range(1, 11):
        for j in range(1, n+1):
            print(f"{i*j:>3}", end='\t')
        print()
            
    return ' '

print(table(12))
    
    
    

  1	  2	  3	  4	  5	  6	  7	  8	  9	 10	 11	 12	
  2	  4	  6	  8	 10	 12	 14	 16	 18	 20	 22	 24	
  3	  6	  9	 12	 15	 18	 21	 24	 27	 30	 33	 36	
  4	  8	 12	 16	 20	 24	 28	 32	 36	 40	 44	 48	
  5	 10	 15	 20	 25	 30	 35	 40	 45	 50	 55	 60	
  6	 12	 18	 24	 30	 36	 42	 48	 54	 60	 66	 72	
  7	 14	 21	 28	 35	 42	 49	 56	 63	 70	 77	 84	
  8	 16	 24	 32	 40	 48	 56	 64	 72	 80	 88	 96	
  9	 18	 27	 36	 45	 54	 63	 72	 81	 90	 99	108	
 10	 20	 30	 40	 50	 60	 70	 80	 90	100	110	120	
 


---
**Assignment 2**

Multiplying square matrices.

Consider two square matrices $A$ and $B$ of size $n\times n$:

$$A = \left (\begin{array}{cccc} a_{11} & a_{12} & \cdots & a_{1n}\\ a_{21} & a_{22} & \cdots & a_{2n}\\ \vdots & \vdots & \ddots & \vdots\\ a_{n1} & a_{n2} & \cdots & a_{nn}\\ \end{array} \right)$$

$$B = \left (\begin{array}{cccc} b_{11} & b_{12} & \cdots & b_{1n}\\ b_{21} & b_{22} & \cdots & b_{2n}\\ \vdots & \vdots & \ddots & \vdots\\ b_{n1} & b_{n2} & \cdots & b_{nn}\\ \end{array} \right)$$

Multiplying gives a new matrix $C$ of size $n\times n$, where the components of $C$ are defined as:

$$c_{ij} = \sum_{k=1}^{n} a_{ik}b_{kj}$$


Write code that given matrix `A` and `B` (both defined as 2D numpy arrays) computes the product `C`. Use nested loops. HINT: you need nested loops of depth 3 (for `i`, `j` and `k`)

TIP: check your result with the numpy function for computing the product of matrices.

In [84]:
# =============== YOUR CODE GOES HERE =================
import numpy as np
n = 5
# define two square matrices as 2D numpy arrays
a = np.random.randint(10, size=(n, n))
b = np.random.randint(10, size=(n, n))
c = np.zeros((n,n))

# compute the product c
for i in range(len(a)):
    for j in range(len(b[0])):
        for k in range(len(b)):
            c[i][j] += a[i][k] * b[k][j]

print(f"Ik: \n{c}")

            
print(f"Numpy: \n{np.dot(a,b)}")
            

Ik: 
[[105.   5.  55.  76.  30.]
 [182.  47. 102. 146. 121.]
 [152.  58.  88. 131. 131.]
 [ 89.  43.  43.  99. 105.]
 [168.  54.  87. 191. 143.]]
Numpy: 
[[105   5  55  76  30]
 [182  47 102 146 121]
 [152  58  88 131 131]
 [ 89  43  43  99 105]
 [168  54  87 191 143]]
