# NOTEBOOK 6 More on sequences
---

## INDEXING AND SLICING

Sequence types (e.g. list, tuple, string, numpy array) can store multiple values. For example:  

`myarray = np.array([1, 5, 2, 42])`  

Here the numpy array `x` contains 4 integers. You can use **indexing** to select 1 or more values from the array. You do that by using square brackets and an index pointing at the position of the value in the array. Below you see a few examples. Note that indexing starts at 0, which means that the first value in an array is at index 0 (and not 1). The basic syntax is:

`item_at_index = mysequence[index]`


In [1]:
# example
import numpy as np

x = np.array([1, 5, 2, 42])
item0 = x[0]  # the first element
item1 = x[1]  # the second element
item3 = x[3]  # the fourth and last element
item_minus1 = x[-1]  # the last element (think of it as counting backward in the list starting at index 0)

# BTW you can use f-strings to print variables in a nice way
print(f'item at index 0 is: {item0}')
print(f'item at index 1 is: {item1}')
print(f'item at index 3 is: {item3}')
print(f'item at index -1 is: {item_minus1}')

item at index 0 is: 1
item at index 1 is: 5
item at index 3 is: 42
item at index -1 is: 42


In [8]:
# you get an error if the index is too large for the length of the array
print(x[6])

IndexError: index 6 is out of bounds for axis 0 with size 4

You can select multiple values. This is called **slicing**. The basic syntax is: 

`mysequence[start:stop]`

with `start` the start index (inclusive) and `stop` the stop index (exclusive). The result is a new sequence (of the same type as `mysequence`) containing the items of `mysequence` at index start, start+1, start+2,..., stop-1. 
You can also defince a step (or stride):

`mysequence[start:stop:stride]`

which selects items at index start, start+stride, start+2*stride, ..., stop-1. 
Let's look at a few examples.


In [2]:
mylist = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

newlist = mylist[0:5]  # stop index is exclusive so you get values at index 0, 1, 2, 3, 4
print(newlist)

[1, 2, 3, 4, 5]


In [4]:
newlist = mylist[3:5]  # stop index is exclusive so you get values at index 3, 4
print(newlist)

[4, 5]


In [5]:
newlist = mylist[3:]  # if you do not specify a stop index it takes all items from start index to the last item
print(newlist)

[4, 5, 6, 7, 8, 9, 10]


In [6]:
newlist = mylist[:3]  # if you do not specify a start index it takes start=0
print(newlist)

[1, 2, 3]


In [12]:
newlist = mylist[1:11:2]  # take a stride (or step) of 2
print(newlist)

[2, 4, 6, 8, 10]


---
**Assignment 6.1**

A measurement is performed in which we measure two quantities $x$ and $y$ at various times $t$. Unfortunately the data in the numpy array defined in the cell below is a bit mixed up. The values in the arrays are: $[t_0, x_0, y_0, t_1, x_1,y_1,t_2, x_2, y_2, \cdots, \text{etc}]$. Write code that creates three numpy arrays `t`, `x` and `y` that contain the data of $t$, $x$ and $y$ respectively. Make use of slicing!

In [119]:
data = np.array([0, 0, 0.05, 1, 1, 0.07, 2, 8, 0.15, 3, 13, 0.16, 4, 18, 0.17, 5, 35, 0.39, 6, 50, 0.41, 7, 50, 0.52, 8,61, 0.56, 9, 62, 0.73, 10, 79, 0.99])

# =============== YOUR CODE GOES HERE =================

array_t = data[0::3]
array_x = data[1::3]
array_y = data[2::3]
print(array_t)
print(array_x)
print(array_y)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.  1.  8. 13. 18. 35. 50. 50. 61. 62. 79.]
[0.05 0.07 0.15 0.16 0.17 0.39 0.41 0.52 0.56 0.73 0.99]


---
**Assignment 6.2**

Use slicing to define the variables `firstname` and `lastname` that contain the first-, and lastname respectively of the defined string.

In [3]:
name = 'Albert Einstein'

# =============== YOUR CODE GOES HERE =================
firstname = name[:6]
lastname = name[7:]

print(firstname)
print(lastname)

Albert
Einstein


The concept of indexing and slicing cannot only be used to get values from the sequence. It can in exactly the same way be used to set values in the sequence. A few examples:

In [27]:
# example

mylist = ['eggs', 'bacon', 'spam']
print(f'Before: {mylist}')

mylist[1] = 'spam'  # set the second item of the sequence
print(f'After: {mylist}')


Before: ['eggs', 'bacon', 'spam']
After: ['eggs', 'spam', 'spam']


In [7]:
# example

mylist = ['eggs', 'bacon', 'spam']
print(f'Before: {mylist}')

mylist[:2] = mylist[1:]   # what happens here?
print(f'After: {mylist}')

Before: ['eggs', 'bacon', 'spam']
After: ['bacon', 'spam', 'spam']


---
**Assignment 6.3**

- Define an array `data` that contains 100 random numbers between 0 and 100 from a uniform distribution.
- Use slicing to multiply the first 50 items of `data` by -1. 

If you did this correctly, the first 50 items of `data` are negative.

In [6]:
# =============== YOUR CODE GOES HERE =================
rng = np.random.default_rng()
data = rng.uniform(low=0,high=100, size=100)

data[:50] = data[:50]*-1

print(data)

[-82.93910705 -46.57349084 -52.00904746 -96.01694911 -63.32132477
 -95.48905049  -7.64742172  -8.30265699 -37.16384728 -19.18416369
 -62.35800417 -38.35199748 -80.8384658  -61.75218295 -79.01135751
 -34.41421786 -57.06354132 -18.60000542 -22.14606983 -98.7485884
 -57.23814361 -63.77139331 -52.71985033 -77.38202117 -34.69202954
 -95.49774929 -48.41276629 -78.03800376 -74.5397725  -44.51665707
 -98.39566342 -97.87215126 -41.72960657 -11.09043577 -14.53133962
 -39.49443605 -37.73050957 -10.89472938 -88.8026356  -26.2006231
 -90.69610042 -51.82268466 -91.66548071 -75.87326629  -5.23696802
 -19.54333906 -88.31123254 -66.07511735 -73.78806587 -96.74624281
  17.59517526  11.56894635   5.85560739  62.19449467  62.15799532
   0.73760724   1.90703132  46.62462504  41.18641953  29.854568
  43.6834393    3.59660575  32.29451478  42.31443376  78.51660215
  16.22908914  80.77384983  17.98591055  59.45488822  36.58227226
  59.76071277  14.03904233  67.90118572  65.88528266  99.16449112
  78.0188614  

---
**Assignment 6.4**

Given is an array `data` that contains positions of a particle over time that experiences Brownian motion along one direction (random walk). The positions are taken at a time interval $\Delta t = 1$ ms.
From this data we want to determine the diffusion coefficient. The diffusion coefficient $D$ is given by:

$$D = \frac{<(\Delta x)^2>}{2 \Delta t}$$

In this equation $<\Delta x>$ is the average of all squared displacements in timestep $\Delta t$. If we take $\Delta t$ to be equal to 1 ms we find that $<\Delta x>$ is given by:

$$\frac{(data[1] - data[0])^2 + (data[2] - data[1])^2 + (data[3] - data[2])^2 + , \text{etc}}{n} $$

with $n$ the number of differences we computed.

Write code that computes the diffusion coefficient of the particle.

In [5]:
data = np.array([0, 1, 2, 1, 0, -1, -2, -3, -4, -3, -4, -5, -4, -3, -4, -5, -4, -5, -4, -3, -4, -5, -4, -5, -4, -5, -6, -5, -6, -7, -6, -7, -8, -9, -10, 
                 -11, -12, -11, -12, -11, -10, -9, -10, -11, -12, -11, -10, -11, -10, -11, -10, -9, -10, -11, -10, -11, -10, -11, -10, -9, -10, -9, -10, 
                 -9, -8, -9, -8, -7, -6, -7, -6, -7, -6, -7, -8, -7, -6, -5, -4, -3, -2, -3, -4, -5, -6, -5, -4, -5, -4, -5, -4, -3, -4, -5, -6, -7, -8, 
                 -7, -8, -7, -8, -7, -6, -7, -6, -7, -6, -7, -6, -5, -6, -5, -4, -5, -6, -5, -6, -5, -6, -7, -6, -7, -8, -9, -10, -11, -12, -13, -12, -11, 
                 -10, -9, -10, -9, -8, -9, -10, -11, -10, -9, -10, -9, -10, -9, -8, -9, -10, -9, -10, -9, -8, -7, -8, -9, -8, -7, -6, -5, -6, -5, -4, -3, 
                 -4, -3, -2, -3, -4, -5, -4, -3, -4, -5, -6, -5, -6, -7, -6, -7, -6, -7, -6, -7, -6, -7, -8, -7, -6, -7, -8, -7, -6, -5, -6, -5, -4, -3, 
                 -4, -5, -4, -3, -2, -1, -2, -1, -2, -3, -2, -1, 0, 1, 0, 1, 0, -1, -2, -1, 0, -1, -2, -1, 0, -1, 0, 1, 0, -1, -2, -1, 0, 1, 0, -1, 0, -1, 
                 -2, -3, -4, -5, -6, -5, -4, -3, -4, -5, -6, -7, -8, -9, -10, -11, -10]) # positions in micrometers

# =============== YOUR CODE GOES HERE =================
datafrom1=data[1::]
datatillmin1=data[:-1]

difference = (datafrom1 - datatillmin1)
dx = np.sum((difference)**2)/len(difference)

dt = 0.001

print(dx)

D = (dx**2)/(2*dt)

print(D)

1.0
500.0
